server:
  port: 9091 #配置端口
  servlet:
    context-path: /basic-web
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  application:
    name: basic-web
  main:
    banner-mode: console                       # 控制Banner打印 OFF(禁止打印Banner)、CONSOLE（打印Banner至控制台）、LOG（打印Banner至日志文件）
    show-banner: on                            # 同上已经过时
    lazy-initialization: false                 # 懒加载
  banner:
#    image:
#      location: banner/banner.jpg              # 设置banner图片位置 默认classpath:banner.gif
#      bitdepth: 4                              # 配置banner图片的ANSI颜色的位深度，默认值是4 支持的值是4（16色）或8（256色）
#      invert: false                            # 配置暗终端主题的图片是否应该倒置，默认值是false
#      margin: 2                                # 配置Banner图片左手图像边距，单位为字符。默认值为2
#      pixelmode: block                         # 配置渲染图像时要使用的像素模式，默认值为TEXT。可选择模式为TEXT和BLOCK
#      width: 76                                # 配置Banner图像的宽度，单位为chars，默认值为76
#      height: 52                               # 配置banner图像的字符高度（默认基于图像高度）
    location: banner/banner.txt                # 设置banner.txt位置 默认位置classpath:banner.txt
    charset: UTF-8                             # 配置banner文件的字符集编码，默认值是UTF-8
  #MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 177214
    url: jdbc:mysql://liqingchen.top:3306/basic_web?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true&remarks=true&useInformationSchema=true
  #flyway配置
  flyway:
    enabled: true
    encoding: UTF-8
    #locations: classpath:/db/db
    #是否允许无序的迁移
    out-of-order: false
    #当初始化好连接时要执行的SQL
    #init-sqls:
    #使用的元数据表名-->版本记录
    table: schema_version_basic_web
    #  开启自动创建flyway元数据表标识 默认: false
    baseline-on-migrate: true
    placeholder-replacement: true
    # 配置占位符(可自定义多个占位符)
    # 自定义占位符: myParam
    # 自定义参数值: value
    placeholders:
      tablePrefix: qingchen_basic_web

